import { realtimeDB } from "@/_lib/firebase/client";
import { ref, onValue } from "firebase/database";
export interface Order {
  id?: string; // optional, generated by push()
  name: string;
  quantity: number;
  status: "pending" | "completed" | "cancelled";
}
export function subscribeOrders(callback: (orders: Order[]) => void) {
  const ordersRef = ref(realtimeDB, "orders");

  const unsubscribe = onValue(ordersRef, (snapshot) => {
    const data = snapshot.val();
    console.log(data);
    const list = data
      ? Object.entries(data).map(([id, item]) => ({
          id,
          ...(item as Order),
        }))
      : [];
    callback(list);
  });

  return unsubscribe; // call this to stop listening
}
